# Generated by Django 6.0.3 on 2026-04-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_phone_created_at_phone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
